import { writeFileSync } from 'node:fs';
import { format, resolveConfig } from 'prettier';
import { mapMetadata } from '../../src/data/maps/map-metadata';
import { loadMap } from '../../src/domain/maps/map-loader';

async function main(): Promise<void> {
  const entries = await Promise.all(
    mapMetadata.map(async (metadata) => {
      const map = await loadMap(metadata.id);
      return [map.id, map.tiles.map((tile) => tile.id)] as const;
    }),
  );
  const outputPath = 'src/data/maps/map-tile-ids.ts';
  const content = `// Generated by npm run generate:tile-ids. Contains no mission data.
import type { MapId } from '../../domain/maps/map.model';
import type { TileId } from '../../domain/maps/tile.model';

export const mapTileIds = ${JSON.stringify(Object.fromEntries(entries))} as const satisfies Readonly<Record<MapId, readonly TileId[]>>;
`;
  writeFileSync(
    outputPath,
    await format(content, { ...(await resolveConfig(outputPath)), parser: 'typescript' }),
    'utf8',
  );
  console.log(`Wrote tile IDs for ${entries.length} maps.`);
}
main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
