import { writeFileSync } from 'node:fs';
import { format, resolveConfig } from 'prettier';
import { loadMap } from '../../src/domain/maps/map-loader';
import type { MapId } from '../../src/domain/maps/map.model';
import type { TileId } from '../../src/domain/maps/tile.model';
import * as oldEnemyData from './old-data/old-enemies';
import { migrateFarmingLocations } from './migrate-farming-locations';

async function main(): Promise<void> {
  const locations = migrateFarmingLocations(
    Object.values(oldEnemyData).sort((a, b) => (a.sortingIndex ?? 0) - (b.sortingIndex ?? 0)),
  );
  const tilesByMap = new Map<MapId, ReadonlySet<TileId>>();
  const missingTiles: string[] = [];
  for (const location of locations) {
    if (location.type !== 'adventure') continue;
    let tiles = tilesByMap.get(location.mapId);
    if (!tiles) {
      const map = await loadMap(location.mapId);
      tiles = new Set(map.tiles.map((tile) => tile.id));
      tilesByMap.set(location.mapId, tiles);
    }
    if (!tiles.has(location.tileId)) {
      missingTiles.push(`${location.enemyId}: ${location.mapId}/${location.tileId}`);
    }
  }
  if (missingTiles.length) {
    console.warn(
      `Warning: ${missingTiles.length} transposed locations reference missing V2 tiles. ` +
        'Preserving them as requested; review the V1 coordinates before using these data.',
    );
    for (const missing of missingTiles) console.warn(`  ${missing}`);
  }
  if (!process.argv.includes('--write')) {
    console.log(`Migrated ${locations.length} farming locations. Use --write to write the file.`);
    return;
  }
  const outputPath = 'src/data/farming-locations.ts';
  const content = `// Generated by npm run migrate:farming -- --write.
// V1 row-column coordinates have been transposed to column-row.
import type { FarmingLocation } from '../domain/farming-location.model';

export const farmingLocations = ${JSON.stringify(locations, null, 2)} as const satisfies readonly FarmingLocation[];
`;
  const formatted = await format(content, {
    ...(await resolveConfig(outputPath)),
    parser: 'typescript',
  });
  writeFileSync(outputPath, formatted, 'utf8');
  console.log(`Wrote ${locations.length} farming locations to ${outputPath}.`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
